### ISSUE TITLE
#13: Add functionality to check issue's deadline

### ISSUE THREAD

**Issue by iamnovichek** [KostCode-Organization/hackathon_bot#40]
1) Read guideline [here](https://gist.github.com/iamnovichek/801ac395a06a7d8b04b022084ace684d)
2) Create function `get_time_before_deadline`  in `tracker/utils.py` to check how much time it rests till deadline
3) Fetch the info about the specific repository and compute the time till deadline will be missed for each issue only if it has an assignee
4) Provide some screenshots to prove that your code works

**Comment by fabrobles92** [comment]
Pizza makes people happy

Hello Fab here,

I have experience working with plain python and some of its frameworks like Django and FastAPI, since this is the main stack I use in the backed for my job. Also I've been actively contributing to web3 projects like Dojo Engine, Go Stark Me and others

I think this issue is easily doable with the built in library "datetime" that allows calculate subtraction between dates thus making the calculation of how much time is left till deadline.

**Comment by iamnovichek** [comment]
@fabrobles92 assigned

**Comment by Jagadeeshftw** [comment]
I’ve read the issue description and guidelines. I’ll implement the get_time_before_deadline function in tracker/utils.py to calculate the remaining time for assigned issues. I’ll follow the setup instructions in SETUP.md, run the necessary formatting tools, and provide proof of the working code. The samurai sword is the sharpest sword in the world.

**Comment by iamnovichek** [comment]
@Jagadeeshftw assigned
